<a href="https://colab.research.google.com/github/bpunar/Numpy-Assignment/blob/main/06_Self_Study_NumPy_Exercise_Student.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Çalışma

### NumPy Array'i Oluşturmak

In [63]:
import numpy as np

In [64]:
np.__version__

'1.21.5'

In [65]:
# code here
np.arange(1,6)

array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [66]:
a = np.array([1,2,3,4,5])
type(a)

numpy.ndarray

In [67]:
np.array([3.14, 4, 2, 13], dtype = "int")

array([ 3,  4,  2, 13])

In [68]:
np.array([3.14, 4, 2, 13], dtype = "float")

array([ 3.14,  4.  ,  2.  , 13.  ])

In [ ]:
# sifirdan array olusturma (np.zeros)

In [69]:
# code here
np.zeros(10, dtype = "int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [70]:
# code here
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# birlerden array olusturma (np.ones)

In [71]:
# code here
np.ones([3,5], dtype = "int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [72]:
# code here
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# belirlenen değerler ile doldurma (np.full)

In [73]:
# code here
np.ones([3,5])*3

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [74]:
np.full([3,5], 3.)

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [75]:
# code here (arange)
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [76]:
# code here (linspace)
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [77]:
# code here (random.normal)
np.random.normal(10, 2, [3, 4])

array([[ 5.18490569,  9.45419916, 12.04649461, 14.91008599],
       [ 8.95261558,  6.50735158, 10.88748723,  8.2842424 ],
       [10.27214416, 10.87130294,  6.04839091,  9.79845114]])

array([[17.36153175, 13.13320486,  7.9751651 , 10.96652924],
       [15.88966379, 14.9596121 ,  0.79541802, 13.03982467],
       [11.16320473,  8.95138261, 11.24850164, 14.35247169]])

In [78]:
# code here (random.randint)
np.random.randint(0, 10, size=[5,2], dtype=int)

array([[8, 3],
       [7, 3],
       [1, 1],
       [0, 7],
       [8, 7]])

array([[5, 8],
       [5, 2],
       [7, 5],
       [7, 7],
       [0, 5]])

### Özellikleri

* **ndim**: _boyut sayısı_
* shape: boyut bilgisi
* size: toplam eleman sayısı
* dtype: array veri tipi

In [79]:
import numpy as np

In [82]:
# code here(random.randint, hihg=10, size=10)
a = np.random.randint(0, 10, size=10, dtype=int)
a

array([9, 1, 6, 9, 9, 6, 9, 7, 9, 1])

array([9, 8, 7, 8, 5, 3, 6, 8, 2, 8])

In [83]:
# code here (find the dimension of a)
np.ndim(a)

1

1

In [84]:
# code here (find the shape of a)
a.shape

(10,)

(10,)

In [85]:
# code here (find the size of a)
np.size(a)

10

10

In [86]:
# code here (find the dtype of a)
a.dtype

dtype('int64')

dtype('int32')

In [87]:
# code here(assign your code to 'b', random.randint, hihg=20, size=(4,6))
b=np.random.randint(0, high=20, size=(4,6))
b

array([[19, 10,  6, 12, 13, 11],
       [17,  4, 10, 12,  1,  1],
       [19,  4,  3,  8,  9, 12],
       [12,  3, 18, 13, 19,  3]])

In [ ]:
b

array([[14, 16,  3,  7,  1],
       [ 3, 16,  2,  6,  0],
       [15,  9,  8,  9, 19],
       [ 3, 10,  4,  6, 15]])

In [88]:
# code here (find the dimension of b)
np.ndim(b)

2

2

In [89]:
# code here (find the shape of b)
b.shape

(4, 6)

(4, 6)

In [ ]:
# code here (find the size of b)

In [80]:
np.size(b)

24

24

In [ ]:
# code here (find the dtype of b)

In [83]:
b.dtype

dtype('int64')

dtype('int32')

# Yeniden Şekillendirme (Reshaping)

In [84]:
import numpy as np

In [ ]:
# code here (arange, start=1, stop=10)

In [86]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# code here (reshape (3,3) your coding above)

In [87]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
a = np.arange(1,10)

In [89]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# code here (find the dimension of a)

In [90]:
np.ndim(a)

1

1

In [96]:
type(a)

numpy.ndarray

In [99]:
a.shape

(9,)

In [ ]:
# code here (reshape a as (1,9) and assign to b)

In [92]:
b = a.reshape(1,9)
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
# code here (find the dimension of b)

In [93]:
np.ndim(b)

2

2

In [98]:
b.shape

(1, 9)

In [97]:
type(b)

numpy.ndarray

### Array Birlestirme (Concatenation)

In [100]:
import numpy as np

In [101]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [ ]:
# code here (concatenate x and y)

In [106]:
np.concatenate((x, y), axis=0)

array([1, 2, 3, 4, 5, 6])

array([1, 2, 3, 4, 5, 6])

In [107]:
z = x+y
z

array([5, 7, 9])

In [108]:
z = np.array([7,8,9])

In [ ]:
# code here (concatenate x, y and z)

In [109]:
np.concatenate((x, y, z), axis=0)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# code here (concatenate z, y and x)

In [110]:
np.concatenate((z, y, x), axis=0)

array([7, 8, 9, 4, 5, 6, 1, 2, 3])

array([7, 8, 9, 4, 5, 6, 1, 2, 3])

In [111]:
a = np.array([[1,2,3], 
              [4,5,6]])

In [ ]:
# code here (concatenate a and a)

In [112]:
np.concatenate((a, a), axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
# code here (concatenate a and a)

In [113]:
np.concatenate((a, a), axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Array Ayırma (Splitting)

In [114]:
import numpy as np

In [184]:
x = np.array([1,2,3,99,99,3,2,1])

In [ ]:
# code here (split x from 3 and 5)

In [185]:
np.split(x, [3, 5, 8], axis=0)

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1]), array([], dtype=int64)]

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [ ]:
# code here (do a tuple unpacking for above splitting in order of a,b,c)

In [186]:
a = np.split(x, [3, 5, 8], axis=0)[0]
a

array([1, 2, 3])

In [188]:
b = np.split(x, [3, 5, 8], axis=0)[1]
b

array([99, 99])

In [189]:
c = np.split(x, [3, 5, 8], axis=0)[2]
c

array([3, 2, 1])

In [ ]:
#iki boyutlu ayırma

In [130]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
# code here (split m)

In [136]:
np.split(m, 2, axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
# code here (split m)

In [137]:
np.split(m, 2, axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

### Array Sıralama (Sorting)

In [138]:
import numpy as np

In [139]:
v = np.array([2,1,4,3,5])

In [140]:
v

array([2, 1, 4, 3, 5])

In [ ]:
# code here (sort v)

In [144]:
v.sort()

In [146]:
np.sort(v)

array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [ ]:
# iki boyutlu array siralama

In [147]:
m = np.random.normal(20,5, (3,3))

In [148]:
m

array([[23.15520008, 19.01961404, 17.1661385 ],
       [13.66425196, 16.01878953, 19.69330724],
       [ 8.22753604, 14.69615246, 18.59461024]])

In [ ]:
# code here (sort m)

In [150]:
np.sort(m, axis=1)

array([[17.1661385 , 19.01961404, 23.15520008],
       [13.66425196, 16.01878953, 19.69330724],
       [ 8.22753604, 14.69615246, 18.59461024]])

array([[11.4711052 , 20.00086064, 28.44452052],
       [15.02090679, 16.0648143 , 23.22445351],
       [ 9.34939833, 20.03722184, 22.39429448]])

In [ ]:
# code here (sort m)

In [151]:
np.sort(m, axis=0)

array([[ 8.22753604, 14.69615246, 17.1661385 ],
       [13.66425196, 16.01878953, 18.59461024],
       [23.15520008, 19.01961404, 19.69330724]])

array([[16.0648143 , 11.4711052 ,  9.34939833],
       [20.00086064, 22.39429448, 15.02090679],
       [20.03722184, 23.22445351, 28.44452052]])

# Index ile Elemanlara Erişmek

In [162]:
import numpy as np
a = np.random.randint(10, size = 10)
a

array([4, 9, 5, 5, 6, 4, 7, 6, 8, 0])

In [ ]:
# code here

In [163]:
a[0] #ilk elemana eriş

4

3

In [164]:
# code here

In [165]:
a[-1] #son elemana eriş

0

6

In [166]:
a[2], a[5], a[9] = [4, 0, 100]

In [ ]:
# code here

In [167]:
a[2]

4

4

In [ ]:
# code here

In [168]:
a[5]

0

0

In [ ]:
# code here

In [169]:
a[9]

100

100

In [170]:
m = np.random.randint(10, size = (3,5))
m

array([[3, 9, 4, 3, 6],
       [5, 6, 7, 4, 0],
       [2, 6, 3, 2, 8]])

In [ ]:
# code here

In [172]:
m[0,0]

3

8

In [ ]:
# code here

In [173]:
m[0,4]

6

6

In [ ]:
# code here

In [174]:
m[1, 4]

0

In [ ]:
# code here (look at the below array)

In [176]:
m[1, 4] = 99

In [177]:
m

array([[ 3,  9,  4,  3,  6],
       [ 5,  6,  7,  4, 99],
       [ 2,  6,  3,  2,  8]])

In [ ]:
# code here

In [178]:
m[2, 3]

2

In [ ]:
# code here (look at the below array)

In [179]:
m[2, 3] = 111
m

array([[  3,   9,   4,   3,   6],
       [  5,   6,   7,   4,  99],
       [  2,   6,   3, 111,   8]])

In [ ]:
m

array([[  8,   4,   2,   4,   6],
       [  5,   6,   4,   2,  99],
       [  8,   0,   0, 111,   6]])

# Slicing ile Elemanlara Erişmek (Array Alt Kümesine Erişmek)

In [190]:
import numpy as np

In [191]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
# code here

In [192]:
a[0:3]

array([20, 21, 22])

array([20, 21, 22])

In [ ]:
# code here

array([20, 21, 22])

In [ ]:
# code here

In [197]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

array([23, 24, 25, 26, 27, 28, 29])

In [ ]:
# code here

In [198]:
a[1::2]

array([21, 23, 25, 27, 29])

array([21, 23, 25, 27, 29])

In [ ]:
# code here

In [199]:
a[0::2]

array([20, 22, 24, 26, 28])

array([20, 22, 24, 26, 28])

In [ ]:
# code here

In [200]:
a[2::2]

array([22, 24, 26, 28])

array([22, 24, 26, 28])

In [ ]:
# code here

In [201]:
a[0::3]

array([20, 23, 26, 29])

array([20, 23, 26, 29])

In [ ]:
#iki boyutlu slice islemleri

In [204]:
m = np.random.randint(10, size = (5,5))
m

array([[8, 0, 8, 6, 5],
       [0, 1, 7, 9, 4],
       [8, 9, 8, 6, 5],
       [1, 5, 1, 6, 3],
       [1, 0, 1, 7, 6]])

In [ ]:
m

array([[2, 1, 8, 3, 8],
       [4, 3, 2, 3, 5],
       [5, 9, 3, 1, 3],
       [3, 1, 6, 9, 4],
       [6, 0, 9, 9, 0]])

In [ ]:
# code here

In [205]:
m[:,0]

array([8, 0, 8, 1, 1])

array([2, 4, 5, 3, 6])

In [ ]:
# code here

In [206]:
m[:,1]

array([0, 1, 9, 5, 0])

array([1, 3, 9, 1, 0])

In [ ]:
# code here

In [207]:
m[:,4]

array([5, 4, 5, 3, 6])

array([8, 5, 3, 4, 0])

In [ ]:
m

array([[2, 1, 8, 3, 8],
       [4, 3, 2, 3, 5],
       [5, 9, 3, 1, 3],
       [3, 1, 6, 9, 4],
       [6, 0, 9, 9, 0]])

In [ ]:
# code here

In [208]:
m

array([[8, 0, 8, 6, 5],
       [0, 1, 7, 9, 4],
       [8, 9, 8, 6, 5],
       [1, 5, 1, 6, 3],
       [1, 0, 1, 7, 6]])

In [ ]:
# code here

In [209]:
m[0,:]

array([8, 0, 8, 6, 5])

array([2, 1, 8, 3, 8])

In [ ]:
# code here

In [210]:
m[1,:]

array([0, 1, 7, 9, 4])

array([4, 3, 2, 3, 5])

In [ ]:
# code here

In [211]:
m[0:2,0:3]

array([[8, 0, 8],
       [0, 1, 7]])

array([[2, 1, 8],
       [4, 3, 2]])

In [ ]:
# code here

In [212]:
m[:,0:2]

array([[8, 0],
       [0, 1],
       [8, 9],
       [1, 5],
       [1, 0]])

array([[2, 1],
       [4, 3],
       [5, 9],
       [3, 1],
       [6, 0]])

In [ ]:
m

array([[2, 1, 8, 3, 8],
       [4, 3, 2, 3, 5],
       [5, 9, 3, 1, 3],
       [3, 1, 6, 9, 4],
       [6, 0, 9, 9, 0]])

In [ ]:
# code here

In [213]:
m[1:3,0:2]

array([[0, 1],
       [8, 9]])

array([[4, 3],
       [5, 9]])

# Alt Küme Üzerinde İşlem Yapmak

In [214]:
import numpy as np
a = np.random.randint(10, size = (5, 5))
a

array([[6, 7, 4, 4, 1],
       [1, 5, 7, 3, 4],
       [4, 7, 8, 4, 7],
       [5, 2, 1, 7, 4],
       [4, 3, 5, 2, 1]])

In [ ]:
# code here

In [218]:
a[0:3,0:2]

array([[6, 7],
       [1, 5],
       [4, 7]])

array([[3, 5],
       [8, 5],
       [9, 0]])

In [ ]:
# code here

In [222]:
a[0:3,0:2][[0,1],[0,1]] = [99999, 8888]
a[0:3,0:2]

array([[99999,     7],
       [    1,  8888],
       [    4,     7]])

array([[99999,     5],
       [    8,   888],
       [    9,     0]])

In [223]:
a

array([[99999,     7,     4,     4,     1],
       [    1,  8888,     7,     3,     4],
       [    4,     7,     8,     4,     7],
       [    5,     2,     1,     7,     4],
       [    4,     3,     5,     2,     1]])

In [ ]:
a

array([[99999,     5,     0,     7,     2],
       [    8,   888,     4,     6,     1],
       [    9,     0,     5,     9,     5],
       [    7,     6,     6,     6,     3],
       [    4,     3,     8,     7,     6]])

In [ ]:
m = np.random.randint(10, size = (5, 5))
m

array([[8, 1, 4, 0, 2],
       [4, 0, 3, 0, 6],
       [4, 1, 4, 0, 3],
       [1, 8, 0, 8, 9],
       [6, 0, 1, 2, 4]])

In [224]:
m = np.random.randint(10, size = (5, 5))
m

array([[7, 4, 4, 2, 7],
       [0, 0, 3, 8, 5],
       [1, 3, 9, 6, 6],
       [7, 6, 2, 4, 0],
       [5, 6, 3, 3, 7]])

In [ ]:
# code here

In [ ]:
#YAPAMADIM

array([[7, 0],
       [7, 5],
       [7, 4]])

In [ ]:
# code here

array([[9999,    0],
       [   9,    3],
       [   5,    1]])

In [ ]:
m

array([[9, 0, 0, 8, 9],
       [9, 3, 4, 1, 9],
       [5, 1, 2, 1, 5],
       [8, 2, 3, 8, 0],
       [5, 7, 6, 3, 8]])

# Fancy Index ile Elemanlara Erişmek

In [1]:
import numpy as np
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
# code here

In [4]:
ind=1
v[ind]

3

3

In [ ]:
# code here

In [5]:

ind=3
v[ind]

9

9

In [ ]:
# code here

In [14]:
v_1 =v.tolist()
v_1

[0, 3, 6, 9, 12, 15, 18, 21, 24, 27]

In [16]:
v[v_1.index(15)]

15

15

In [ ]:
# code here

In [28]:
v_1[1:6:2]

[3, 9, 15]

[3, 9, 15]

In [30]:
al_getir = [1,3,5]

In [31]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
# code here

In [32]:
v[1:6:2]

array([ 3,  9, 15])

array([ 3,  9, 15])

In [ ]:
#iki boyutta fancy

In [37]:
m = np.arange(9).reshape((3,3))

In [38]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [40]:
m[satir, sutun]

array([1, 5])

In [ ]:
#basit index ile fancy index

In [41]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [42]:
m[0, [1,2]]

array([1, 2])

In [ ]:
#slice ile fancy

In [43]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

# Koşullu Eleman İşlemleri

In [44]:
import numpy as np
v = np.array([1, 2, 3, 4, 5])

In [45]:
v < 3

array([ True,  True, False, False, False])

In [46]:
v[v < 3]

array([1, 2])

In [ ]:
# code here

In [47]:
v[v > 3]

array([4, 5])

In [49]:
# code here
v[v>2]

array([3, 4, 5])

array([3, 4, 5])

In [51]:
# code here
v[v<4]

array([1, 2, 3])

array([1, 2, 3])

In [53]:
# code here
v[v==3]

array([3])

array([3])

In [55]:
# code here
v[v!=3]

array([1, 2, 4, 5])

array([1, 2, 4, 5])

In [56]:
v

array([1, 2, 3, 4, 5])

In [58]:
# code here
v*2

array([ 2,  4,  6,  8, 10])

array([ 2,  4,  6,  8, 10])

In [60]:
# code here
v*2/10

array([0.2, 0.4, 0.6, 0.8, 1. ])

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [62]:
# code here
v**2

array([ 1,  4,  9, 16, 25])

array([ 1,  4,  9, 16, 25], dtype=int32)

# Matematiksel İşlemler

Bu bölüm bilgi ve tekrar maksatlı konulmuştur.

In [90]:
import numpy as np
v = np.array([1, 2, 3, 4, 5])

In [91]:
v - 1

array([0, 1, 2, 3, 4])

In [92]:
v * 5

array([ 5, 10, 15, 20, 25])

In [93]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [ ]:
#ufunc

In [94]:
np.subtract(v, 1)

array([0, 1, 2, 3, 4])

In [95]:
np.add(v, 1)

array([2, 3, 4, 5, 6])

In [96]:
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [97]:
np.divide(v, 3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [98]:
v**2

array([ 1,  4,  9, 16, 25])

In [99]:
v**3

array([  1,   8,  27,  64, 125])

In [100]:
np.power(v, 3)

array([  1,   8,  27,  64, 125])

In [101]:
v % 2

array([1, 0, 1, 0, 1])

In [102]:
np.mod(v, 2)

array([1, 0, 1, 0, 1])

In [103]:
np.absolute(np.array([-3]))

array([3])

In [104]:
np.sin(360)

0.9589157234143065

In [105]:
np.cos(180)

-0.5984600690578581

In [106]:
v = np.array([1,2,3])

In [107]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [108]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [109]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

In [ ]:
?np

# İstatistiksel Hesaplamalar

In [110]:
v

array([1, 2, 3])

In [111]:
np.mean(v)

2.0

In [112]:
v.sum()

6

In [113]:
v.min()

1

* np.mean(arr,axis=0) | Returns mean along specific axis

* arr.sum() | Returns sum of arr

* arr.min() | Returns minimum value of arr

* arr.max(axis=0) | Returns maximum value of specific axis

* np.var(arr) | Returns the variance of array

* np.std(arr,axis=1) | Returns the standard deviation of specific axis

* arr.corrcoef() | Returns correlation coefficient of array

# NumPy ile İki Bilinmeyenli Denklem Çözümü

In [114]:
import numpy as np

**5 * x0 + x1 = 12  
x0 + 3 * x1 = 10**

In [115]:
a = np.array([[5,1], [1,3]])
b = np.array([12,10])

In [116]:
a

array([[5, 1],
       [1, 3]])

In [117]:
b

array([12, 10])

In [118]:
x = np.linalg.solve(a, b)
x

array([1.85714286, 2.71428571])